FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

COPY .env /app/.env

EXPOSE 8000

ENV NAME World

CMD ["sh", "-c", "python create_tables.py && uvicorn app:app --host 0.0.0.0 --port 8000"]
