# Stage 1: Build
FROM node:20-alpine3.17 AS builder

WORKDIR /app

# Copy package manager files and install dependencies
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Production
FROM node:20-alpine3.17 AS production

WORKDIR /app

# Copy the built application and dependencies from the builder stage
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

# Copy next.config.js if it exists
COPY next.config.js ./next.config.js

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]
